Repository City-of-Helsinki/helsinki-design-system, pull requests merged in 2020-12, with the labels that each got.

#333 [Fix] Documentation templates
  site/examples/component.mdx
  site/examples/design_token.mdx
  site/examples/page.mdx
Labels: bug

#332 [Content] Updated What's new for 0.17.0
  site/docs/about/new.mdx
Labels: documentation

#335 [Content] What's new and Roadmap updates for 0.18.0
  site/docs/about/new.mdx
  site/docs/about/roadmap.mdx
Labels: documentation

#317 [Feature] Search field component
  packages/react/.loki/reference/chrome_iphone7_Components_SearchInput_Default.png
  packages/react/.loki/reference/chrome_iphone7_Components_SearchInput_With_suggestions.png
  packages/react/.loki/reference/chrome_iphone7_Components_SearchInput_With_suggestions_and_highlighting.png
  packages/react/.loki/reference/chrome_iphone7_Components_SearchInput_With_suggestions_spinner.png
  packages/react/.loki/reference/chrome_laptop_Components_SearchInput_Default.png
  packages/react/.loki/reference/chrome_laptop_Components_SearchInput_With_suggestions.png
  packages/react/.loki/reference/chrome_laptop_Components_SearchInput_With_suggestions_and_highlighting.png
  packages/react/.loki/reference/chrome_laptop_Components_SearchInput_With_suggestions_spinner.png
  packages/react/rollup.config.js
  packages/react/src/components/index.ts
  packages/react/src/components/searchInput/SearchInput.module.scss
  packages/react/src/components/searchInput/SearchInput.stories.tsx
  packages/react/src/components/searchInput/SearchInput.test.tsx
  packages/react/src/components/searchInput/SearchInput.tsx
  packages/react/src/components/searchInput/__snapshots__/SearchInput.test.tsx.snap
  packages/react/src/components/searchInput/index.ts
  packages/react/src/components/searchInput/useSuggestions.ts
  packages/react/src/hooks/useDebouncedEffect.ts
  packages/react/src/hooks/useShowLoadingSpinner.ts
  packages/react/src/internal/dropdownMenu/DropdownMenu.tsx
  packages/react/src/utils/cancellablePromise.ts
  site/docs/components/search_input.mdx
  site/docs/components/text_fields.mdx
Labels: component

#342 [FIX] Fix placeholders in firefox
  packages/core/src/components/text-input/text-input.css
  packages/react/src/components/dropdown/combobox/Combobox.module.scss
Labels: bug

#339 [FIX] Add logoLanguage prop to Footer component
  packages/react/src/components/footer/Footer.tsx
Labels: enhancement

#331 [Feature] Accordion
  packages/react/.loki/reference/chrome_iphone7_Components_Accordion_Card.png
  packages/react/.loki/reference/chrome_iphone7_Components_Accordion_Custom.png
  packages/react/.loki/reference/chrome_iphone7_Components_Accordion_Custom_accordion.png
  packages/react/.loki/reference/chrome_iphone7_Components_Accordion_Custom_theme.png
  packages/react/.loki/reference/chrome_iphone7_Components_Accordion_Default.png
  packages/react/.loki/reference/chrome_laptop_Components_Accordion_Card.png
  packages/react/.loki/reference/chrome_laptop_Components_Accordion_Custom.png
  packages/react/.loki/reference/chrome_laptop_Components_Accordion_Custom_accordion.png
  packages/react/.loki/reference/chrome_laptop_Components_Accordion_Custom_theme.png
  packages/react/.loki/reference/chrome_laptop_Components_Accordion_Default.png
  packages/react/rollup.config.js
  packages/react/src/components/accordion/Accordion.module.scss
  packages/react/src/components/accordion/Accordion.stories.tsx
  packages/react/src/components/accordion/Accordion.test.tsx
  packages/react/src/components/accordion/Accordion.tsx
  packages/react/src/components/accordion/__snapshots__/Accordion.test.tsx.snap
  packages/react/src/components/accordion/index.ts
  packages/react/src/components/accordion/useAccordion.ts
  packages/react/src/components/index.ts
  site/docs/components/accordion.mdx
  site/docs/components/card.mdx
  site/docs/components/component_overview.mdx
  site/docs/components/status_label.mdx
Labels: component

#347 [Content] Updated What's new and Roadmap pages for version 0.19.0
  site/docs/about/new.mdx
  site/docs/about/roadmap.mdx
Labels: documentation
