Repository City-of-Helsinki/helsinki-design-system, pull requests merged in 2020-11, with the labels that each got.

#307 [Content] Added accordion and form validation to roadmap
  site/docs/about/roadmap.mdx
Labels: documentation

#308 [Feature] Finalize tag implementation
  packages/core/src/components/tag/tag.css
  packages/core/src/components/tag/tag.stories.js
  packages/react/rollup.config.js
  packages/react/src/components/tag/Tag.module.scss
  packages/react/src/components/tag/Tag.stories.tsx
  packages/react/src/components/tag/Tag.test.tsx
  packages/react/src/components/tag/Tag.tsx
  packages/react/src/components/tag/__snapshots__/Tag.test.tsx.snap
  packages/react/src/hooks/useTheme.tsx
  packages/react/src/internal/selectedItems/SelectedItems.tsx
  packages/react/src/utils/getModulesClassName.ts
  site/docs/components/component_overview.mdx
  site/docs/components/tag.mdx
Labels: component

#311 [Feature] LoadingSpinner component
  packages/core/src/components/all.css
  packages/core/src/components/loading-spinner/loading-spinner.css
  packages/core/src/components/loading-spinner/loading-spinner.stories.js
  packages/react/rollup.config.js
  packages/react/src/components/index.ts
  packages/react/src/components/loadingSpinner/LoadingSpinner.module.scss
  packages/react/src/components/loadingSpinner/LoadingSpinner.stories.tsx
  packages/react/src/components/loadingSpinner/LoadingSpinner.test.tsx
  packages/react/src/components/loadingSpinner/LoadingSpinner.tsx
  packages/react/src/components/loadingSpinner/__snapshots__/LoadingSpinner.test.tsx.snap
  packages/react/src/components/loadingSpinner/index.ts
  packages/react/src/components/loadingSpinner/useNotificationArea.ts
  packages/react/src/components/tag/Tag.module.scss
  packages/react/src/components/tag/Tag.tsx
  site/docs/components/component_overview.mdx
  site/docs/components/notification.mdx
  site/docs/components/spinner.mdx
Labels: component

#292 [Feature] SelectionGroup component
  packages/core/src/components/all.css
  packages/core/src/components/selection-group/selection-group.css
  packages/core/src/components/selection-group/selection-group.stories.js
  packages/react/rollup.config.js
  packages/react/src/components/checkbox/Checkbox.tsx
  packages/react/src/components/index.ts
  packages/react/src/components/radioButton/RadioButton.tsx
  packages/react/src/components/selectionGroup/SelectionGroup.module.scss
  packages/react/src/components/selectionGroup/SelectionGroup.stories.tsx
  packages/react/src/components/selectionGroup/SelectionGroup.test.tsx
  packages/react/src/components/selectionGroup/SelectionGroup.tsx
  packages/react/src/components/selectionGroup/__snapshots__/SelectionGroup.test.tsx.snap
  packages/react/src/components/selectionGroup/index.ts
  packages/react/src/internal/field-label/FieldLabel.module.scss
  packages/react/src/styles/_common.scss
  site/docs/components/checkbox.mdx
  site/docs/components/component_overview.mdx
  site/docs/components/radio_button.mdx
  site/docs/components/selection_group.mdx
Labels: component

#313 [FIX] Add missing aria-hidden attribute to icon in Notification component
  packages/react/src/components/notification/Notification.tsx
  packages/react/src/components/notification/__snapshots__/Notification.test.tsx.snap
Labels: enhancement

#319 [Change] Remove border-radius from all components
  packages/core/src/components/checkbox/checkbox.css
  packages/core/src/components/text-input/text-input.css
  packages/react/src/components/dropdown/_dropdown.common.scss
Labels: enhancement

#318 [Feature] Koros as core components
  packages/core/src/components/all.css
  packages/core/src/components/koros/koros.css
  packages/core/src/components/koros/koros.stories.js
  packages/react/src/components/koros/Koros.stories.tsx
  packages/react/src/components/koros/Koros.tsx
  site/docs/components/component_overview.mdx
  site/docs/components/koros.mdx
Labels: component

#312 [Feature] Container component
  packages/core/src/components/container/container.css
  packages/core/src/components/container/container.stories.js
  packages/react/rollup.config.js
  packages/react/src/components/container/Container.module.scss
  packages/react/src/components/container/Container.stories.tsx
  packages/react/src/components/container/Container.test.tsx
  packages/react/src/components/container/Container.tsx
  packages/react/src/components/container/__snapshots__/Container.test.tsx.snap
  packages/react/src/components/container/index.ts
  packages/react/src/components/index.ts
  site/docs/design_tokens/breakpoints.mdx
  site/docs/guidelines/grid.mdx
Labels: component
