Repository City-of-Helsinki/helsinki-design-system, pull requests merged in 2020-08, with the labels that each got.

#208 [Fix] Removed unnecessary dot from HDS mail address
  site/docs/about/support.mdx
Labels: bug

#211 Documentation site front page image improvements
  site/docs/get_started/for_designers.mdx
  site/docs/get_started/for_developers.mdx
  site/docs/get_started/get_started.mdx
  site/docs/index.mdx
  site/static/for_contributors.svg
  site/static/for_designers.svg
  site/static/for_developers.svg
  site/static/start-contribute-block.svg
  site/static/start-contribute.svg
  site/static/start-design-block.svg
  site/static/start-design.svg
  site/static/start-develop-block.svg
  site/static/start-develop.svg
  site/static/start-intro-block.svg
Labels: documentation

#194 Update typography documentation
  site/docs/design_tokens/typography.mdx
Labels: documentation

#204 [Feature] Implement StatusLabel component
  packages/core/src/components/status-label/status-label.css
  packages/core/src/components/status-label/status-label.stories.js
  packages/react/src/components/status-label/StatusLabel.module.css
  packages/react/src/components/status-label/StatusLabel.stories.tsx
  packages/react/src/components/status-label/StatusLabel.test.tsx
  packages/react/src/components/status-label/StatusLabel.tsx
  packages/react/src/components/status-label/__snapshots__/StatusLabel.test.tsx.snap
  packages/react/src/index.ts
  site/docs/components/status_label.mdx
  site/docs/design_tokens/colour.mdx
Labels: component

#210 [Content] Update roadmap
  site/docs/about/roadmap.mdx
Labels: documentation

#218 [Fix] Documentation site paragraph margins
  site/src/gatsby-theme-docz/theme/styles.js
Labels: bug

#212 [Feature] Implement updated Notification design
  packages/core/src/components/notification/notification.css
  packages/core/src/components/notification/notification.stories.js
  packages/react/package.json
  packages/react/rollup.config.js
  packages/react/src/components/notification/DismissableNotification.module.css
  packages/react/src/components/notification/DismissableNotification.stories.tsx
  packages/react/src/components/notification/DismissableNotification.test.tsx
  packages/react/src/components/notification/DismissableNotification.tsx
  packages/react/src/components/notification/Notification.module.css
  packages/react/src/components/notification/Notification.stories.tsx
  packages/react/src/components/notification/Notification.test.tsx
  packages/react/src/components/notification/Notification.tsx
  packages/react/src/components/notification/__snapshots__/DismissableNotification.test.tsx.snap
  packages/react/src/components/notification/__snapshots__/Notification.test.tsx.snap
  packages/react/src/components/tooltip/Tooltip.tsx
  packages/react/src/index.ts
  yarn.lock
Labels: component

#231 [Fix] Reference equality comparison in Dropdown multiselect mode
  CHANGELOG.md
  packages/react/src/components/dropdown/Dropdown.stories.tsx
  packages/react/src/components/dropdown/Dropdown.tsx
Labels: bug

#227 [Change] Breakpoint and container width tokens
  packages/design-tokens/tokens/breakpoint/breakpoint.json
  packages/design-tokens/tokens/breakpoint/container-width.json
  site/docs/design_tokens/breakpoints.mdx
  site/static/grid-breakpoint-demonstration.png
Labels: documentation, enhancement

#222 [Fix] Multi-select tab bug
  packages/react/src/components/dropdown/Dropdown.tsx
Labels: bug
