Repository City-of-Helsinki/helsinki-design-system, pull requests merged in 2020-09, with the labels that each got.

#219 [Documentation] Add status labels for component documentation
  site/docs/components/buttons.mdx
  site/docs/components/checkbox.mdx
  site/docs/components/component_overview.mdx
  site/docs/components/dropdown.mdx
  site/docs/components/icons.mdx
  site/docs/components/koros.mdx
  site/docs/components/navigation.mdx
  site/docs/components/notification.mdx
  site/docs/components/radio_button.mdx
  site/docs/components/status_label.mdx
  site/docs/components/text_fields.mdx
  yarn.lock
Labels: documentation

#230 [Content] Documentation guidelines
  site/README.md
  site/docs/contributing.mdx
  site/examples/component.mdx
  site/examples/design_token.mdx
  site/examples/page.mdx
Labels: documentation

#209 [Documentation] Date and time guidelines
  site/docs/about/statement.mdx
  site/docs/guidelines/accessibility.mdx
  site/docs/guidelines/data_formats.mdx
Labels: documentation

#243 [Content] Logo component documentation
  site/docs/components/component_overview.mdx
  site/docs/components/logo.mdx
  yarn.lock
Labels: documentation

#248 [Content] Colour accessibility examples
  site/docs/design_tokens/colour.mdx
  site/src/components/ColorContrast.js
  site/src/gatsby-theme-docz/theme/styles.js
Labels: documentation

#247 [Fix] Documentation site search placeholder and favicon download
  site/docs/visual_elements/logo.mdx
  site/src/gatsby-theme-docz/components/Sidebar/index.js
Labels: documentation, enhancement

#252 [Fix] Small documentation fixes
  site/docs/components/component_overview.mdx
  site/docs/guidelines/localization.mdx
Labels: bug, documentation
