Repository City-of-Helsinki/helsinki-design-system, pull requests merged in 2020-10, with the labels that each got.

#260 Update HDS Roadmap
  site/docs/about/roadmap.mdx
Labels: documentation

#261 [Fix] Small documentation site updates
  site/docs/about/support.mdx
  site/doczrc.js
Labels: documentation

#264 [Fix] Small visual fixes to documentation
  site/docs/Contributing/before-contributing.mdx
  site/docs/about/support.mdx
Labels: bug

#269 [Accessibility] Koros component
  packages/react/src/components/koros/Koros.tsx
  packages/react/src/components/koros/__snapshots__/Koros.test.tsx.snap
Labels: enhancement

#266 [Fix] Documentation broken links
  site/docs/Contributing/design.mdx
  site/docs/Contributing/implemenation.mdx
  site/docs/about/support.mdx
  site/docs/components/component_overview.mdx
  site/docs/design_tokens/colour.mdx
  site/docs/get_started/for_designers.mdx
  site/docs/get_started/for_developers.mdx
  site/docs/index.mdx
Labels: bug, documentation

#259 [Content] Placeholders documentation and downloads
  site/docs/visual_elements/placeholders.mdx
  site/static/assets/placeholders/HDS-placeholder-image.zip
  site/static/assets/placeholders/HDS-placeholder-user-image.zip
  site/static/assets/placeholders/image/image-l.png
  site/static/assets/placeholders/image/image-l@2x.png
  site/static/assets/placeholders/image/image-l@3x.png
  site/static/assets/placeholders/image/image-m.png
  site/static/assets/placeholders/image/image-m@2x.png
  site/static/assets/placeholders/image/image-m@3x.png
  site/static/assets/placeholders/image/image-s.png
  site/static/assets/placeholders/image/image-s@2x.png
  site/static/assets/placeholders/image/image-s@3x.png
  site/static/assets/placeholders/image/image-xl.png
  site/static/assets/placeholders/image/image-xl@2x.png
  site/static/assets/placeholders/image/image-xl@3x.png
  site/static/assets/placeholders/user-image/user-image-l.png
  site/static/assets/placeholders/user-image/user-image-l@2x.png
  site/static/assets/placeholders/user-image/user-image-l@3x.png
  site/static/assets/placeholders/user-image/user-image-m.png
  site/static/assets/placeholders/user-image/user-image-m@2x.png
  site/static/assets/placeholders/user-image/user-image-m@3x.png
  site/static/assets/placeholders/user-image/user-image-s.png
  site/static/assets/placeholders/user-image/user-image-s@2x.png
  site/static/assets/placeholders/user-image/user-image-s@3x.png
Labels: documentation

#270 [Accessibility] Navigation component search
  packages/react/src/components/navigation/navigation-search/NavigationSearch.tsx
  packages/react/src/components/navigation/navigation-search/__snapshots__/NavigationSearch.test.tsx.snap
Labels: bug, enhancement

#271 [Accessibility] Removed aria-checked from Checkbox and Radio button
  packages/react/src/components/checkbox/Checkbox.tsx
  packages/react/src/components/checkbox/__snapshots__/Checkbox.test.tsx.snap
  packages/react/src/components/radioButton/RadioButton.tsx
  packages/react/src/components/radioButton/__snapshots__/RadioButton.test.tsx.snap
Labels: enhancement

#272 [Accessibility] Logo component
  packages/react/src/components/logo/Logo.tsx
  packages/react/src/components/logo/__snapshots__/Logo.test.tsx.snap
  packages/react/src/components/navigation/__snapshots__/Navigation.test.tsx.snap
  packages/react/src/components/navigation/navigation-actions/__snapshots__/NavigationActions.test.tsx.snap
  packages/react/src/components/navigation/navigation-dropdown/__snapshots__/NavigationDropdown.test.tsx.snap
  packages/react/src/components/navigation/navigation-item/__snapshots__/NavigationItem.test.tsx.snap
  packages/react/src/components/navigation/navigation-language-selector/__snapshots__/NavigationLanguageSelector.test.tsx.snap
  packages/react/src/components/navigation/navigation-row/__snapshots__/NavigationRow.test.tsx.snap
  packages/react/src/components/navigation/navigation-search/__snapshots__/NavigationSearch.test.tsx.snap
  packages/react/src/components/navigation/navigation-user/__snapshots__/NavigationUser.test.tsx.snap
  site/docs/components/logo.mdx
Labels: enhancement

#263 [Accessibility] Small accessibility additions to documentation
  site/docs/components/dropdown.mdx
  site/docs/components/icons.mdx
  site/docs/design_tokens/colour.mdx
Labels: documentation

#275 [Fix] Removed HTML Title from Gatsby wrapper.jsx
  site/src/gatsby-theme-docz/wrapper.jsx
Labels: bug

#273 [Accessibility] Fix notification accessibility issues
  packages/core/src/components/notification/notification.css
  packages/core/src/components/notification/notification.stories.js
  packages/react/src/components/notification/Notification.module.css
  packages/react/src/components/notification/Notification.test.tsx
  packages/react/src/components/notification/Notification.tsx
  packages/react/src/components/notification/__snapshots__/Notification.test.tsx.snap
  site/docs/components/notification.mdx
Labels: enhancement

#258 [Feature] Refactor dropdown
  packages/core/src/components/all.css
  packages/core/src/components/tag/tag.css
  packages/core/src/components/tag/tag.stories.js
  packages/react/package.json
  packages/react/rollup.config.js
  packages/react/src/components/dropdown/Dropdown.stories.tsx
  packages/react/src/components/dropdown/_dropdown.common.scss
  packages/react/src/components/dropdown/combobox/Combobox.module.scss
  packages/react/src/components/dropdown/combobox/Combobox.stories.tsx
  packages/react/src/components/dropdown/combobox/Combobox.test.tsx
  packages/react/src/components/dropdown/combobox/Combobox.tsx
  packages/react/src/components/dropdown/combobox/index.ts
  packages/react/src/components/dropdown/dropdown/Dropdown.module.css
  packages/react/src/components/dropdown/dropdown/Dropdown.test.tsx
  packages/react/src/components/dropdown/dropdown/Dropdown.tsx
  packages/react/src/components/dropdown/dropdown/__snapshots__/Dropdown.test.tsx.snap
  packages/react/src/components/dropdown/dropdown/index.ts
  packages/react/src/components/dropdown/dropdownUtils.ts
  packages/react/src/components/dropdown/index.ts
  packages/react/src/components/dropdown/select/Select.module.scss
  packages/react/src/components/dropdown/select/Select.stories.tsx
  packages/react/src/components/dropdown/select/Select.test.tsx
  packages/react/src/components/dropdown/select/Select.tsx
  packages/react/src/components/dropdown/select/__snapshots__/Select.test.tsx.snap
  packages/react/src/components/dropdown/select/index.ts
  packages/react/src/components/index.ts
  packages/react/src/components/navigation/navigation-dropdown/NavigationDropdown.module.css
  packages/react/src/components/navigation/navigation-language-selector/NavigationLanguageSelector.module.css
  packages/react/src/components/tag/Tag.module.scss
  packages/react/src/components/tag/Tag.stories.tsx
  packages/react/src/components/tag/Tag.test.tsx
  packages/react/src/components/tag/Tag.tsx
  packages/react/src/components/tag/__snapshots__/Tag.test.tsx.snap
  packages/react/src/components/tag/index.ts
  packages/react/src/internal/dropdownMenu/DropdownMenu.tsx
  packages/react/src/internal/field-label/__snapshots__/FieldLabel.test.tsx.snap
  packages/react/src/internal/required-indicator/RequiredIndicator.tsx
  packages/react/src/internal/required-indicator/__snapshots__/RequiredIndicator.test.tsx.snap
  packages/react/src/internal/selectedItems/SelectedItems.module.scss
  packages/react/src/internal/selectedItems/SelectedItems.tsx
  packages/react/src/styles/_common.scss
  packages/react/src/utils/setComponentTheme.ts
  site/docs/components/component_overview.mdx
  site/docs/components/dropdown.mdx
  site/docs/design_tokens/typography.mdx
  yarn.lock
Labels: component, enhancement

#278 [Content] Documentation site accessibility guidelines and statement
  site/docs/about/statement.mdx
  site/docs/guidelines/accessibility.mdx
  site/docs/resources.mdx
Labels: documentation

#282 [Change] Update color token names and values
  packages/core/src/components/button/button.css
  packages/core/src/components/checkbox/checkbox.css
  packages/core/src/components/notification/notification.css
  packages/core/src/components/radio-button/radio-button.css
  packages/core/src/components/tag/tag.css
  packages/core/src/components/text-input/text-input.css
  packages/design-tokens/tokens/color/brand/brick.json
  packages/design-tokens/tokens/color/brand/bus.json
  packages/design-tokens/tokens/color/brand/coat-of-arms-blue.json
  packages/design-tokens/tokens/color/brand/coat-of-arms-gold.json
  packages/design-tokens/tokens/color/brand/coat-of-arms-silver.json
  packages/design-tokens/tokens/color/brand/coat-of-arms.json
  packages/design-tokens/tokens/color/brand/copper.json
  packages/design-tokens/tokens/color/brand/engel.json
  packages/design-tokens/tokens/color/brand/fog.json
  packages/design-tokens/tokens/color/brand/gold.json
  packages/design-tokens/tokens/color/brand/metro.json
  packages/design-tokens/tokens/color/brand/silver.json
  packages/design-tokens/tokens/color/brand/summer.json
  packages/design-tokens/tokens/color/brand/suomenlinna.json
  packages/design-tokens/tokens/color/brand/tram.json
  packages/react/src/components/dropdown/_dropdown.common.scss
  packages/react/src/components/dropdown/dropdown/Dropdown.module.css
  packages/react/src/components/footer/Footer.module.scss
  packages/react/src/components/imageWithCard/ImageWithCard.module.css
  packages/react/src/components/navigation/Navigation.module.css
  packages/react/src/components/section/Section.module.css
  packages/react/src/components/tooltip/Tooltip.module.css
  site/docs/design_tokens/colour.mdx
Labels: enhancement

#287 [Fix] Added aria-label to documentation site external link icon
  site/src/components/Link.js
Labels: enhancement

#279 [Content] Form pattern guidelines
  site/docs/patterns/forms.mdx
  site/doczrc.js
  site/static/patterns/form/form-choosing-combobox-multi@2x.png
  site/static/patterns/form/form-choosing-combobox@2x.png
  site/static/patterns/form/form-choosing-dropdown-multi@2x.png
  site/static/patterns/form/form-choosing-dropdown@2x.png
  site/static/patterns/form/form-choosing-secondary@2x.png
  site/static/patterns/form/form-choosing-select-checkbox@2x.png
  site/static/patterns/form/form-choosing-select-checkboxgroup@2x.png
  site/static/patterns/form/form-choosing-select-radio@2x.png
  site/static/patterns/form/form-choosing-submit@2x.png
  site/static/patterns/form/form-choosing-supplementary@2x.png
  site/static/patterns/form/form-choosing-textarea@2x.png
  site/static/patterns/form/form-choosing-textinput@2x.png
  site/static/patterns/form/form-elements-action@2x.png
  site/static/patterns/form/form-elements-contol@2x.png
  site/static/patterns/form/form-elements-contols@2x.png
  site/static/patterns/form/form-elements-icon@2x.png
  site/static/patterns/form/form-elements-label@2x.png
  site/static/patterns/form/form-elements-required@2x.png
  site/static/patterns/form/form-focus-multi@2x.png
  site/static/patterns/form/form-focus-single@2x.png
  site/static/patterns/form/form-grouping@2x.png
  site/static/patterns/form/form-guiding-assistive@2x.png
  site/static/patterns/form/form-guiding-headings@2x.png
  site/static/patterns/form/form-guiding-instructions@2x.png
  site/static/patterns/form/form-guiding-placeholder@2x.png
  site/static/patterns/form/form-guiding-tooltip@2x.png
  site/static/patterns/form/form-layout-actions-field@2x.png
  site/static/patterns/form/form-layout-actions-form@2x.png
  site/static/patterns/form/form-layout-grid@2x.png
  site/static/patterns/form/form-layout-horizontal@2x.png
  site/static/patterns/form/form-layout-spacing@2x.png
  site/static/patterns/form/form-layout-vertical@2x.png
  site/static/patterns/form/form-layout-width@2x.png
  site/static/patterns/form/form-segmenting@2x.png
  site/static/patterns/form/form-states-active-disabled@2x.png
  site/static/patterns/form/form-states-error@2x.png
  site/static/patterns/form/form-states-filled@2x.png
  site/static/patterns/form/form-states-focus@2x.png
  site/static/patterns/form/form-states-hover@2x.png
  site/static/patterns/form/form-states-selected@2x.png
  site/static/patterns/form/form-steps@2x.png
Labels: pattern

#276 [Feature] Card component
  packages/core/src/components/all.css
  packages/core/src/components/card/card.css
  packages/core/src/components/card/card.stories.js
  packages/react/src/components/card/Card.module.scss
  packages/react/src/components/card/Card.stories.tsx
  packages/react/src/components/card/Card.test.tsx
  packages/react/src/components/card/Card.tsx
  packages/react/src/components/card/__snapshots__/Card.test.tsx.snap
  packages/react/src/components/card/index.ts
  packages/react/src/components/index.ts
  site/docs/components/card.mdx
  site/docs/components/component_overview.mdx
  yarn.lock
Labels: component

#283 [Feature] Tooltip
  packages/react/package.json
  packages/react/src/components/dropdown/_dropdown.common.scss
  packages/react/src/components/dropdown/combobox/Combobox.stories.tsx
  packages/react/src/components/dropdown/combobox/Combobox.tsx
  packages/react/src/components/dropdown/select/Select.stories.tsx
  packages/react/src/components/dropdown/select/Select.tsx
  packages/react/src/components/textInput/TextInput.stories.tsx
  packages/react/src/components/textInput/TextInput.tsx
  packages/react/src/components/textInput/__snapshots__/TextInput.test.tsx.snap
  packages/react/src/components/textarea/TextArea.stories.tsx
  packages/react/src/components/textarea/TextArea.tsx
  packages/react/src/components/textarea/__snapshots__/TextArea.test.tsx.snap
  packages/react/src/components/tooltip/Tooltip.module.css
  packages/react/src/components/tooltip/Tooltip.module.scss
  packages/react/src/components/tooltip/Tooltip.stories.tsx
  packages/react/src/components/tooltip/Tooltip.test.tsx
  packages/react/src/components/tooltip/Tooltip.tsx
  packages/react/src/components/tooltip/__snapshots__/Tooltip.test.tsx.snap
  packages/react/src/internal/field-label/FieldLabel.module.css
  packages/react/src/internal/field-label/FieldLabel.module.scss
  packages/react/src/internal/field-label/FieldLabel.tsx
  packages/react/src/internal/input-wrapper/InputWrapper.tsx
  site/docs/components/component_overview.mdx
  site/docs/components/text_fields.mdx
  site/docs/components/tooltip.mdx
  yarn.lock
Labels: component, enhancement

#294 [Fix] Added a note to the Card documentation about interactability
  site/docs/components/card.mdx
Labels: documentation

#296 [Change] Moved general documentation guidelines from README to doc site
  site/README.md
  site/docs/Contributing/documentation.mdx
Labels: documentation

#291 [Documentation] Fixed form pattern example images
  site/static/patterns/form/form-elements-action@2x.png
  site/static/patterns/form/form-elements-icon@2x.png
  site/static/patterns/form/form-guiding-instructions@2x.png
  site/static/patterns/form/form-guiding-placeholder@2x.png
Labels: documentation

#303 [Fix Fixed broken Storybook links in the Tooltip documentation
  site/docs/components/tooltip.mdx
Labels: bug

#274 [Accessibility] Button fixes
  packages/core/src/components/button/button.css
  packages/core/src/components/button/button.stories.js
  packages/react/src/components/button/Button.stories.tsx
  packages/react/src/components/button/Button.tsx
  packages/react/src/components/navigation/navigationUser/NavigationUser.tsx
  site/docs/components/buttons.mdx
Labels: enhancement

#301 [Documentation] Doc site updates for beta release
  site/docs/about/new.mdx
  site/docs/about/roadmap.mdx
  site/src/gatsby-theme-docz/components/Sidebar/index.js
Labels: documentation

#285 [Documentation] Component status update for beta release
  site/docs/components/buttons.mdx
  site/docs/components/card.mdx
  site/docs/components/checkbox.mdx
  site/docs/components/component_overview.mdx
  site/docs/components/dropdown.mdx
  site/docs/components/footer.mdx
  site/docs/components/icons.mdx
  site/docs/components/koros.mdx
  site/docs/components/logo.mdx
  site/docs/components/navigation.mdx
  site/docs/components/notification.mdx
  site/docs/components/radio_button.mdx
  site/docs/components/status_label.mdx
  site/docs/components/text_fields.mdx
  site/docs/components/tooltip.mdx
Labels: documentation

#306 [Fix] Add icon to Supplementary button documentation example
  packages/core/src/components/button/button.stories.js
  packages/react/src/components/button/Button.stories.tsx
  site/docs/components/buttons.mdx
Labels: bug, documentation
