Repository City-of-Helsinki/helsinki-design-system, pull requests merged in 2021-06, with the labels that each got.

#462 [Content] Toggle button documentation
  site/docs/components/checkbox.mdx
  site/docs/components/toggle.mdx
Labels: component, documentation

#457 Feature/fieldset
  packages/core/src/components/fieldset/fieldset.css
  packages/core/src/components/fieldset/fieldset.stories.js
  packages/react/.loki/reference/chrome_iphone7_Components_Fieldset_Default.png
  packages/react/.loki/reference/chrome_iphone7_Components_Fieldset_With_Border.png
  packages/react/.loki/reference/chrome_iphone7_Components_Fieldset_With_Selection_Group.png
  packages/react/.loki/reference/chrome_laptop_Components_Fieldset_Default.png
  packages/react/.loki/reference/chrome_laptop_Components_Fieldset_With_Border.png
  packages/react/.loki/reference/chrome_laptop_Components_Fieldset_With_Selection_Group.png
  packages/react/rollup.config.js
  packages/react/src/components/fieldset/Fieldset.module.scss
  packages/react/src/components/fieldset/Fieldset.stories.tsx
  packages/react/src/components/fieldset/Fieldset.test.tsx
  packages/react/src/components/fieldset/Fieldset.tsx
  packages/react/src/components/fieldset/__snapshots__/Fieldset.test.tsx.snap
  packages/react/src/components/fieldset/index.ts
  packages/react/src/components/index.ts
  site/docs/components/fieldset.mdx
Labels: component, documentation

#455 Fixed "from" to "form" typo in Storybook validation examples
  packages/react/src/examples/forms/validationDynamic.stories.tsx
  packages/react/src/examples/forms/validationHybrid.stories.tsx
  packages/react/src/examples/forms/validationStatic.stories.tsx
Labels: bug, documentation

#470 Feature/toggle button
  packages/react/.loki/reference/chrome_iphone7_Components_ToggleButton_Custom_theme.png
  packages/react/.loki/reference/chrome_iphone7_Components_ToggleButton_Default.png
  packages/react/.loki/reference/chrome_iphone7_Components_ToggleButton_Disabled.png
  packages/react/.loki/reference/chrome_iphone7_Components_ToggleButton_Inline.png
  packages/react/.loki/reference/chrome_iphone7_Components_ToggleButton_With_tooltip.png
  packages/react/.loki/reference/chrome_laptop_Components_ToggleButton_Custom_theme.png
  packages/react/.loki/reference/chrome_laptop_Components_ToggleButton_Default.png
  packages/react/.loki/reference/chrome_laptop_Components_ToggleButton_Disabled.png
  packages/react/.loki/reference/chrome_laptop_Components_ToggleButton_Inline.png
  packages/react/.loki/reference/chrome_laptop_Components_ToggleButton_With_tooltip.png
  packages/react/rollup.config.js
  packages/react/src/components/index.ts
  packages/react/src/components/toggleButton/ToggleButton.module.scss
  packages/react/src/components/toggleButton/ToggleButton.stories.tsx
  packages/react/src/components/toggleButton/ToggleButton.test.tsx
  packages/react/src/components/toggleButton/ToggleButton.tsx
  packages/react/src/components/toggleButton/__snapshots__/ToggleButton.test.tsx.snap
  packages/react/src/components/toggleButton/index.ts
  site/docs/components/checkbox.mdx
  site/docs/components/component_overview.mdx
  site/docs/components/toggle.mdx
Labels: component, documentation

#456 [Content] Documentation for error messages related to multiple input fields
  site/docs/patterns/form_validation.mdx
  site/static/patterns/form-validation/multiple-fields-validation@2x.png
Labels: documentation
