Repository City-of-Helsinki/helsinki-design-system, pull requests merged in 2021-03, with the labels that each got.

#382 Hds roadmap 2021
  site/docs/about/roadmap.mdx
Labels: documentation

#372 [Fix] Added active link state to Navigation examples
  packages/react/.loki/reference/chrome_laptop_Components_Navigation_Custom_theme.png
  packages/react/.loki/reference/chrome_laptop_Components_Navigation_Default.png
  packages/react/.loki/reference/chrome_laptop_Components_Navigation_Inline.png
  packages/react/src/components/navigation/Navigation.stories.tsx
  site/docs/components/navigation.mdx
Labels: documentation

#369 [Fix] Changed Localisation page URL to use BR English
  site/docs/guidelines/localisation.mdx
Labels: bug

#366 [Fix] Remove unwanted footer "border" in safari
  packages/react/src/components/footer/Footer.module.scss
  packages/react/src/components/footer/Footer.tsx
  packages/react/src/components/footer/__snapshots__/Footer.test.tsx.snap
  packages/react/src/components/footer/footerBase/__snapshots__/FooterBase.test.tsx.snap
  packages/react/src/components/footer/footerItem/__snapshots__/FooterItem.test.tsx.snap
  packages/react/src/components/footer/footerItemGroup/__snapshots__/FooterItemGroup.test.tsx.snap
  packages/react/src/components/footer/footerNavigation/__snapshots__/FooterNavigation.test.tsx.snap
  packages/react/src/components/footer/footerSoMe/__snapshots__/FooterSoMe.test.tsx.snap
  packages/react/src/components/footer/footerUtilities/__snapshots__/FooterUtilities.test.tsx.snap
Labels: bug

#365 [Tooling] Improve scaffolding script for react components
  packages/react/.templates/new-component/NewComponent.module.scss
  packages/react/.templates/new-component/NewComponent.stories.tsx
  packages/react/.templates/new-component/NewComponent.test.tsx
  packages/react/.templates/new-component/NewComponent.tsx
Labels: enhancement

#349 [Feature] DateInput
  packages/core/src/components/text-input/text-input.css
  packages/react/.loki/reference/chrome_iphone7_Components_DateInput_Default.png
  packages/react/.loki/reference/chrome_iphone7_Components_DateInput_Localization.png
  packages/react/.loki/reference/chrome_iphone7_Components_DateInput_Without_confirmation.png
  packages/react/.loki/reference/chrome_iphone7_Components_DateInput_Without_date_picker.png
  packages/react/.loki/reference/chrome_laptop_Components_DateInput_Default.png
  packages/react/.loki/reference/chrome_laptop_Components_DateInput_Localization.png
  packages/react/.loki/reference/chrome_laptop_Components_DateInput_Without_confirmation.png
  packages/react/.loki/reference/chrome_laptop_Components_DateInput_Without_date_picker.png
  packages/react/package.json
  packages/react/rollup.config.js
  packages/react/src/components/dateInput/DateInput.module.scss
  packages/react/src/components/dateInput/DateInput.stories.tsx
  packages/react/src/components/dateInput/DateInput.test.tsx
  packages/react/src/components/dateInput/DateInput.tsx
  packages/react/src/components/dateInput/__snapshots__/DateInput.test.tsx.snap
  packages/react/src/components/dateInput/components/datePicker/DatePicker.module.scss
  packages/react/src/components/dateInput/components/datePicker/DatePicker.tsx
  packages/react/src/components/dateInput/components/datePicker/defaults/defaultProps.ts
  packages/react/src/components/dateInput/components/datePicker/index.ts
  packages/react/src/components/dateInput/components/datePicker/types/DayPickerProps.ts
  packages/react/src/components/dateInput/components/datePicker/types/index.ts
  packages/react/src/components/dateInput/components/day/Day.tsx
  packages/react/src/components/dateInput/components/day/index.ts
  packages/react/src/components/dateInput/components/head/Head.tsx
  packages/react/src/components/dateInput/components/head/getWeekdaysNames.ts
  packages/react/src/components/dateInput/components/head/index.ts
  packages/react/src/components/dateInput/components/monthNavigation/MonthNavigation.tsx
  packages/react/src/components/dateInput/components/monthNavigation/index.ts
  packages/react/src/components/dateInput/components/monthTable/MonthTable.tsx
  packages/react/src/components/dateInput/components/monthTable/index.ts
  packages/react/src/components/dateInput/components/weekRow/WeekRow.tsx
  packages/react/src/components/dateInput/components/weekRow/index.tsx
  packages/react/src/components/dateInput/context/DatePickerContext.tsx
  packages/react/src/components/dateInput/index.ts
  packages/react/src/components/index.ts
  packages/react/src/components/textInput/TextInput.module.css
  packages/react/src/components/textInput/TextInput.tsx
  packages/react/src/utils/scrollIntoViewIfNeeded.ts
  site/docs/components/component_overview.mdx
  site/docs/components/date_input.mdx
  site/docs/guidelines/data_formats.mdx
  yarn.lock
Labels: component

#364 [Feature] TimeInput
  packages/react/.loki/reference/chrome_iphone7_Components_TimeInput_Default.png
  packages/react/.loki/reference/chrome_iphone7_Components_TimeInput_Example.png
  packages/react/.loki/reference/chrome_laptop_Components_TimeInput_Default.png
  packages/react/.loki/reference/chrome_laptop_Components_TimeInput_Example.png
  packages/react/package.json
  packages/react/rollup.config.js
  packages/react/src/components/index.ts
  packages/react/src/components/timeInput/TimeInput.module.scss
  packages/react/src/components/timeInput/TimeInput.stories.tsx
  packages/react/src/components/timeInput/TimeInput.test.tsx
  packages/react/src/components/timeInput/TimeInput.tsx
  packages/react/src/components/timeInput/__snapshots__/TimeInput.test.tsx.snap
  packages/react/src/components/timeInput/index.ts
  site/docs/components/component_overview.mdx
  site/docs/components/time_input.mdx
  yarn.lock
Labels: component, waiting-for-accessibility-audit

#402 [Fix] TextInput error state examples (HDS-658)
  site/docs/components/text_fields.mdx
Labels: bug

#400 [Fix] Broken/incorrect documentation links
  site/docs/components/component_overview.mdx
  site/docs/components/time_input.mdx
Labels: bug, documentation

#398 [Documentation] Improvements to the body text scaling documentation
  site/docs/design_tokens/typography.mdx
Labels: documentation, enhancement

#367 [Feature] Loading button
  packages/core/src/components/button/button.css
  packages/core/src/components/button/button.stories.js
  packages/react/.loki/reference/chrome_iphone7_Components_Button_Loading.png
  packages/react/.loki/reference/chrome_iphone7_Components_Button_Loading_On_Click.png
  packages/react/.loki/reference/chrome_laptop_Components_Button_Loading.png
  packages/react/.loki/reference/chrome_laptop_Components_Button_Loading_On_Click.png
  packages/react/src/components/button/Button.module.scss
  packages/react/src/components/button/Button.stories.tsx
  packages/react/src/components/button/Button.test.tsx
  packages/react/src/components/button/Button.tsx
  packages/react/src/components/button/__snapshots__/Button.test.tsx.snap
  packages/react/src/components/button/_button.common.scss
  packages/react/src/components/dateInput/__snapshots__/DateInput.test.tsx.snap
  site/docs/components/buttons.mdx
Labels: component, waiting-for-accessibility-audit

#407 [Content] Icon set 3
  packages/core/src/icons/all.css
  packages/core/src/icons/ui/icon-customer-bot-negative.css
  packages/core/src/icons/ui/icon-customer-bot-neutral.css
  packages/core/src/icons/ui/icon-customer-bot-positive.css
  packages/core/src/icons/ui/icon-document.css
  packages/core/src/icons/ui/icon-headphones.css
  packages/core/src/icons/ui/icon-save-diskette-fill.css
  packages/core/src/icons/ui/icon-save-diskette.css
  packages/core/src/icons/ui/icon-text-bold.css
  packages/core/src/icons/ui/icon-text-italic.css
  packages/core/src/icons/ui/icon-text-tool.css
  packages/core/src/svg/ui/customer-bot-negative.svg
  packages/core/src/svg/ui/customer-bot-neutral.svg
  packages/core/src/svg/ui/customer-bot-positive.svg
  packages/core/src/svg/ui/document.svg
  packages/core/src/svg/ui/headphones.svg
  packages/core/src/svg/ui/save-diskette-fill.svg
  packages/core/src/svg/ui/save-diskette.svg
  packages/core/src/svg/ui/text-bold.svg
  packages/core/src/svg/ui/text-italic.svg
  packages/core/src/svg/ui/text-tool.svg
  packages/react/src/icons/index.ts
  packages/react/src/icons/ui/IconCustomerBotNegative.tsx
  packages/react/src/icons/ui/IconCustomerBotNeutral.tsx
  packages/react/src/icons/ui/IconCustomerBotPositive.tsx
  packages/react/src/icons/ui/IconDocument.tsx
  packages/react/src/icons/ui/IconHeadphones.tsx
  packages/react/src/icons/ui/IconSaveDiskette.tsx
  packages/react/src/icons/ui/IconSaveDisketteFill.tsx
  packages/react/src/icons/ui/IconTextBold.tsx
  packages/react/src/icons/ui/IconTextItalic.tsx
  packages/react/src/icons/ui/IconTextTool.tsx
  site/docs/visual_elements/icons.mdx
Labels: component

#406 Add loading-button aria-label
  packages/react/src/components/button/Button.tsx
  packages/react/src/components/button/__snapshots__/Button.test.tsx.snap
Labels: component, enhancement
