Repository City-of-Helsinki/helsinki-design-system, pull requests merged in 2021-04, with the labels that each got.

#413 Feature/phone input
  packages/core/src/components/phone-input/phone-input.stories.js
  packages/react/.loki/reference/chrome_iphone7_Components_PhoneInput_Default.png
  packages/react/.loki/reference/chrome_iphone7_Components_PhoneInput_Disabled.png
  packages/react/.loki/reference/chrome_iphone7_Components_PhoneInput_With_a_default_value.png
  packages/react/.loki/reference/chrome_iphone7_Components_PhoneInput_With_select_countrycode.png
  packages/react/.loki/reference/chrome_laptop_Components_PhoneInput_Default.png
  packages/react/.loki/reference/chrome_laptop_Components_PhoneInput_Disabled.png
  packages/react/.loki/reference/chrome_laptop_Components_PhoneInput_With_a_default_value.png
  packages/react/.loki/reference/chrome_laptop_Components_PhoneInput_With_select_countrycode.png
  packages/react/rollup.config.js
  packages/react/src/components/dropdown/combobox/Combobox.tsx
  packages/react/src/components/index.ts
  packages/react/src/components/numberInput/NumberInput.tsx
  packages/react/src/components/phoneInput/PhoneInput.stories.tsx
  packages/react/src/components/phoneInput/PhoneInput.test.tsx
  packages/react/src/components/phoneInput/PhoneInput.tsx
  packages/react/src/components/phoneInput/__snapshots__/PhoneInput.test.tsx.snap
  packages/react/src/components/phoneInput/index.ts
  packages/react/src/components/timeInput/TimeInput.tsx
  packages/react/src/utils/mergeRefWithInternalRef.ts
  site/docs/components/component_overview.mdx
  site/docs/components/phone_input.mdx
Labels: component

#412 [Fix] Content overlap in the Select component with long labels
  packages/react/src/components/dropdown/select/Select.module.scss
  packages/react/src/components/dropdown/select/Select.tsx
Labels: bug

#404 Feature/dialog
  packages/react/.loki/reference/chrome_iphone7_Components_Dialog_Confirmation.png
  packages/react/.loki/reference/chrome_iphone7_Components_Dialog_Danger.png
  packages/react/.loki/reference/chrome_iphone7_Components_Dialog_Scrollable_confirmation.png
  packages/react/.loki/reference/chrome_laptop_Components_Dialog_Confirmation.png
  packages/react/.loki/reference/chrome_laptop_Components_Dialog_Danger.png
  packages/react/.loki/reference/chrome_laptop_Components_Dialog_Scrollable_confirmation.png
  packages/react/rollup.config.js
  packages/react/src/components/dialog/Dialog.module.scss
  packages/react/src/components/dialog/Dialog.stories.tsx
  packages/react/src/components/dialog/Dialog.test.tsx
  packages/react/src/components/dialog/Dialog.tsx
  packages/react/src/components/dialog/DialogContext.tsx
  packages/react/src/components/dialog/__snapshots__/Dialog.test.tsx.snap
  packages/react/src/components/dialog/_dialog.common.scss
  packages/react/src/components/dialog/dialogActionButtons/DialogActionButtons.module.scss
  packages/react/src/components/dialog/dialogActionButtons/DialogActionButtons.tsx
  packages/react/src/components/dialog/dialogContent/DialogContent.module.scss
  packages/react/src/components/dialog/dialogContent/DialogContent.tsx
  packages/react/src/components/dialog/dialogHeader/DialogHeader.module.scss
  packages/react/src/components/dialog/dialogHeader/DialogHeader.tsx
  packages/react/src/components/dialog/index.ts
  packages/react/src/components/index.ts
  site/docs/components/component_overview.mdx
  site/docs/components/dialog.mdx
  yarn.lock
Labels: component

#419 [Change] Start using fill icons (HDS-575, -577, -578)
  site/static/patterns/form-validation/error-summary@2x.png
  site/static/patterns/form-validation/form-states-error@2x.png
  site/static/patterns/form-validation/form-validation-message-error@2x.png
  site/static/patterns/form-validation/form-validation-message-success@2x.png
  site/static/patterns/form-validation/validation-pattern-example@2x.png
Labels: documentation, enhancement

#423 Make doc examples more DRY
  packages/react/src/components/dialog/Dialog.stories.tsx
  site/docs/components/dialog.mdx
Labels: enhancement

#424 Replace notification icons with fill-icons
  packages/core/src/components/notification/notification.css
  packages/core/src/components/notification/notification.stories.js
  packages/react/.loki/reference/chrome_iphone7_Components_ErrorSummary_Default.png
  packages/react/.loki/reference/chrome_iphone7_Components_ErrorSummary_Large.png
  packages/react/.loki/reference/chrome_iphone7_Components_Notification_Alert.png
  packages/react/.loki/reference/chrome_iphone7_Components_Notification_Default.png
  packages/react/.loki/reference/chrome_iphone7_Components_Notification_Dismissible.png
  packages/react/.loki/reference/chrome_iphone7_Components_Notification_Error.png
  packages/react/.loki/reference/chrome_iphone7_Components_Notification_Large.png
  packages/react/.loki/reference/chrome_iphone7_Components_Notification_Playground.png
  packages/react/.loki/reference/chrome_iphone7_Components_Notification_Small.png
  packages/react/.loki/reference/chrome_iphone7_Components_Notification_Success.png
  packages/react/.loki/reference/chrome_laptop_Components_ErrorSummary_Default.png
  packages/react/.loki/reference/chrome_laptop_Components_ErrorSummary_Large.png
  packages/react/.loki/reference/chrome_laptop_Components_Notification_Alert.png
  packages/react/.loki/reference/chrome_laptop_Components_Notification_Default.png
  packages/react/.loki/reference/chrome_laptop_Components_Notification_Dismissible.png
  packages/react/.loki/reference/chrome_laptop_Components_Notification_Error.png
  packages/react/.loki/reference/chrome_laptop_Components_Notification_Large.png
  packages/react/.loki/reference/chrome_laptop_Components_Notification_Playground.png
  packages/react/.loki/reference/chrome_laptop_Components_Notification_Small.png
  packages/react/.loki/reference/chrome_laptop_Components_Notification_Success.png
  packages/react/src/components/errorSummary/ErrorSummary.tsx
  packages/react/src/components/errorSummary/__snapshots__/ErrorSummary.test.tsx.snap
  packages/react/src/components/notification/Notification.tsx
  packages/react/src/components/notification/__snapshots__/Notification.test.tsx.snap
  site/docs/components/notification.mdx
  site/static/patterns/form-validation/error-summary@2x.png
  site/static/patterns/form-validation/form-states-error@2x.png
  site/static/patterns/form-validation/form-validation-message-error@2x.png
  site/static/patterns/form-validation/form-validation-message-success@2x.png
  site/static/patterns/form-validation/validation-pattern-example@2x.png
Labels: enhancement

#425 Use fill-icon in text-field error and success texts
  packages/core/src/components/selection-group/selection-group.css
  packages/core/src/components/text-input/text-input.css
  packages/react/.loki/reference/chrome_iphone7_Components_SelectionGroup_Invalid.png
  packages/react/.loki/reference/chrome_iphone7_Components_TextArea_Invalid.png
  packages/react/.loki/reference/chrome_iphone7_Components_TextArea_Success.png
  packages/react/.loki/reference/chrome_iphone7_Components_TextInput_Invalid.png
  packages/react/.loki/reference/chrome_iphone7_Components_TextInput_Success.png
  packages/react/.loki/reference/chrome_laptop_Components_SelectionGroup_Invalid.png
  packages/react/.loki/reference/chrome_laptop_Components_TextArea_Invalid.png
  packages/react/.loki/reference/chrome_laptop_Components_TextArea_Success.png
  packages/react/.loki/reference/chrome_laptop_Components_TextInput_Invalid.png
  packages/react/.loki/reference/chrome_laptop_Components_TextInput_Success.png
Labels: enhancement

#428 Feature/status label icon
  packages/core/src/components/status-label/status-label.css
  packages/core/src/components/status-label/status-label.stories.js
  packages/react/.loki/reference/chrome_iphone7_Components_Status_label_Alert.png
  packages/react/.loki/reference/chrome_iphone7_Components_Status_label_Error.png
  packages/react/.loki/reference/chrome_iphone7_Components_Status_label_Icons.png
  packages/react/.loki/reference/chrome_iphone7_Components_Status_label_Info.png
  packages/react/.loki/reference/chrome_iphone7_Components_Status_label_Neutral.png
  packages/react/.loki/reference/chrome_iphone7_Components_Status_label_Playground.png
  packages/react/.loki/reference/chrome_iphone7_Components_Status_label_Success.png
  packages/react/.loki/reference/chrome_laptop_Components_Status_label_Alert.png
  packages/react/.loki/reference/chrome_laptop_Components_Status_label_Error.png
  packages/react/.loki/reference/chrome_laptop_Components_Status_label_Icons.png
  packages/react/.loki/reference/chrome_laptop_Components_Status_label_Info.png
  packages/react/.loki/reference/chrome_laptop_Components_Status_label_Neutral.png
  packages/react/.loki/reference/chrome_laptop_Components_Status_label_Playground.png
  packages/react/.loki/reference/chrome_laptop_Components_Status_label_Success.png
  packages/react/src/components/statusLabel/StatusLabel.module.css
  packages/react/src/components/statusLabel/StatusLabel.stories.tsx
  packages/react/src/components/statusLabel/StatusLabel.tsx
  site/docs/components/status_label.mdx
Labels: enhancement

#429 Fix dateinput ref-property
  packages/react/src/components/dateInput/DateInput.tsx
Labels: bug

#432 Fix/dateinput min width
  packages/react/src/components/dateInput/components/datePicker/DatePicker.module.scss
Labels: bug

#422 [Fix] Remove redundant LockOpen icon rows from the icon docs table
  site/docs/visual_elements/icons.mdx
Labels: bug

#435 Remove beta texts
  README.md
  site/docs/guidelines/accessibility.mdx
  site/src/gatsby-theme-docz/components/Sidebar/index.js
Labels: documentation
