Repository City-of-Helsinki/helsinki-design-system, pull requests merged in 2021-09, with the labels that each got.

#523 Fix/number input on change
  packages/react/src/components/numberInput/NumberInput.test.tsx
  packages/react/src/components/numberInput/NumberInput.tsx
Labels: bug

#517 new try on the typo fix
  site/docs/resources.mdx
Labels: bug, documentation

#473 Side navigation component
  packages/react/.loki/reference/chrome_iphone7_Components_SideNavigation_Auto_Collapse_Other_Opened.png
  packages/react/.loki/reference/chrome_iphone7_Components_SideNavigation_Custom_Theme.png
  packages/react/.loki/reference/chrome_iphone7_Components_SideNavigation_Default.png
  packages/react/.loki/reference/chrome_iphone7_Components_SideNavigation_With_Icons.png
  packages/react/.loki/reference/chrome_laptop_Components_SideNavigation_Auto_Collapse_Other_Opened.png
  packages/react/.loki/reference/chrome_laptop_Components_SideNavigation_Custom_Theme.png
  packages/react/.loki/reference/chrome_laptop_Components_SideNavigation_Default.png
  packages/react/.loki/reference/chrome_laptop_Components_SideNavigation_With_Icons.png
  packages/react/package.json
  packages/react/rollup.config.js
  packages/react/src/components/index.ts
  packages/react/src/components/sideNavigation/SideNavigation.module.scss
  packages/react/src/components/sideNavigation/SideNavigation.stories.tsx
  packages/react/src/components/sideNavigation/SideNavigation.test.tsx
  packages/react/src/components/sideNavigation/SideNavigation.tsx
  packages/react/src/components/sideNavigation/SideNavigationContext.tsx
  packages/react/src/components/sideNavigation/__snapshots__/SideNavigation.test.tsx.snap
  packages/react/src/components/sideNavigation/index.ts
  packages/react/src/components/sideNavigation/mainLevel/MainLevel.module.scss
  packages/react/src/components/sideNavigation/mainLevel/MainLevel.tsx
  packages/react/src/components/sideNavigation/subLevel/SubLevel.module.scss
  packages/react/src/components/sideNavigation/subLevel/SubLevel.tsx
  site/docs/components/component_overview.mdx
  site/docs/components/side_navigation.mdx
  yarn.lock
Labels: component

#535 [Content] Add missing components to the form pattern documentation
  site/docs/patterns/forms.mdx
  site/static/patterns/form/form-choosing-combobox-multi@2x.png
  site/static/patterns/form/form-choosing-combobox@2x.png
  site/static/patterns/form/form-choosing-dateinput@2x.png
  site/static/patterns/form/form-choosing-dropdown-multi@2x.png
  site/static/patterns/form/form-choosing-dropdown@2x.png
  site/static/patterns/form/form-choosing-numberinput@2x.png
  site/static/patterns/form/form-choosing-passwordinput@2x.png
  site/static/patterns/form/form-choosing-phonenumberinput@2x.png
  site/static/patterns/form/form-choosing-select-togglebutton@2x.png
  site/static/patterns/form/form-choosing-textarea@2x.png
  site/static/patterns/form/form-choosing-textinput@2x.png
  site/static/patterns/form/form-choosing-timeinput@2x.png
  site/static/patterns/form/form-states-focus@2x.png
Labels: documentation

#530 [Change] Accordion improvements
  packages/react/.loki/reference/chrome_iphone7_Components_Accordion_Custom.png
  packages/react/.loki/reference/chrome_iphone7_Components_Accordion_Initially_open.png
  packages/react/.loki/reference/chrome_laptop_Components_Accordion_Custom.png
  packages/react/.loki/reference/chrome_laptop_Components_Accordion_Initially_open.png
  packages/react/src/components/accordion/Accordion.module.scss
  packages/react/src/components/accordion/Accordion.stories.tsx
  packages/react/src/components/accordion/Accordion.test.tsx
  packages/react/src/components/accordion/Accordion.tsx
  packages/react/src/components/accordion/__snapshots__/Accordion.test.tsx.snap
  site/docs/components/accordion.mdx
Labels: enhancement

#526 [Change] Documentation example heading color
  packages/react/src/examples/forms/validation.scss
  packages/react/src/examples/forms/validationDynamic.stories.tsx
  packages/react/src/examples/forms/validationHybrid.stories.tsx
  packages/react/src/examples/forms/validationStatic.stories.tsx
  site/static/patterns/form-validation/multiple-fields-validation@2x.png
  site/static/patterns/form-validation/validation-pattern-example@2x.png
  site/static/patterns/form/form-focus-multi@2x.png
  site/static/patterns/form/form-focus-single@2x.png
  site/static/patterns/form/form-guiding-headings@2x.png
  site/static/patterns/form/form-guiding-instructions@2x.png
  site/static/patterns/form/form-segmenting@2x.png
  site/static/patterns/form/form-steps@2x.png
Labels: documentation

#521 Feature/fileinput
  packages/core/src/components/text-input/text-input.css
  packages/react/.loki/reference/chrome_iphone7_Components_FileInput_Disabled.png
  packages/react/.loki/reference/chrome_iphone7_Components_FileInput_Disabled_Drag_And_Drop.png
  packages/react/.loki/reference/chrome_iphone7_Components_FileInput_Multiple.png
  packages/react/.loki/reference/chrome_iphone7_Components_FileInput_Playground.png
  packages/react/.loki/reference/chrome_iphone7_Components_FileInput_Required.png
  packages/react/.loki/reference/chrome_iphone7_Components_FileInput_Single.png
  packages/react/.loki/reference/chrome_iphone7_Components_FileInput_With_Drag_And_Drop.png
  packages/react/.loki/reference/chrome_laptop_Components_FileInput_Disabled.png
  packages/react/.loki/reference/chrome_laptop_Components_FileInput_Disabled_Drag_And_Drop.png
  packages/react/.loki/reference/chrome_laptop_Components_FileInput_Multiple.png
  packages/react/.loki/reference/chrome_laptop_Components_FileInput_Playground.png
  packages/react/.loki/reference/chrome_laptop_Components_FileInput_Required.png
  packages/react/.loki/reference/chrome_laptop_Components_FileInput_Single.png
  packages/react/.loki/reference/chrome_laptop_Components_FileInput_With_Drag_And_Drop.png
  packages/react/rollup.config.js
  packages/react/src/components/fileInput/FileInput.module.scss
  packages/react/src/components/fileInput/FileInput.stories.tsx
  packages/react/src/components/fileInput/FileInput.test.tsx
  packages/react/src/components/fileInput/FileInput.tsx
  packages/react/src/components/fileInput/__snapshots__/FileInput.test.tsx.snap
  packages/react/src/components/fileInput/index.ts
  packages/react/src/components/index.ts
  site/docs/components/component_overview.mdx
  site/docs/components/file_input.mdx
Labels: component
