Repository City-of-Helsinki/helsinki-design-system, pull requests merged in 2021-05, with the labels that each got.

#449 Feature/split lokitests
  .github/workflows/development.yml
Labels: enhancement

#448 Fix/postcss vulnerability
  packages/core/package.json
  yarn.lock
Labels: dependencies

#444 Feature/tag height
  packages/core/src/components/tag/tag.css
  packages/react/.loki/reference/chrome_iphone7_Components_Dropdowns_Select_Multi_select_example.png
  packages/react/.loki/reference/chrome_iphone7_Components_Tag_Clickable_tag.png
  packages/react/.loki/reference/chrome_iphone7_Components_Tag_Custom_Theme.png
  packages/react/.loki/reference/chrome_iphone7_Components_Tag_Default.png
  packages/react/.loki/reference/chrome_iphone7_Components_Tag_Deletable_tag.png
  packages/react/.loki/reference/chrome_laptop_Components_Dropdowns_Select_Multi_select_example.png
  packages/react/.loki/reference/chrome_laptop_Components_Tag_Clickable_tag.png
  packages/react/.loki/reference/chrome_laptop_Components_Tag_Custom_Theme.png
  packages/react/.loki/reference/chrome_laptop_Components_Tag_Default.png
  packages/react/.loki/reference/chrome_laptop_Components_Tag_Deletable_tag.png
  packages/react/src/components/dropdown/select/Select.stories.tsx
  packages/react/src/components/tag/Tag.module.scss
  packages/react/src/components/tag/Tag.stories.tsx
  packages/react/src/internal/selectedItems/SelectedItems.module.scss
Labels: enhancement

#445 Fix/datepicker position
  packages/react/src/components/dateInput/DateInput.module.scss
  packages/react/src/components/dateInput/DateInput.test.tsx
  packages/react/src/components/dateInput/DateInput.tsx
  packages/react/src/components/dateInput/__snapshots__/DateInput.test.tsx.snap
  packages/react/src/components/dateInput/components/datePicker/DatePicker.module.scss
  packages/react/src/components/dateInput/components/monthTable/MonthTable.tsx
Labels: bug, enhancement

#451 Added links to colour usage example to the Colour documentation page
  site/docs/design_tokens/colour.mdx
Labels: documentation
