Repository City-of-Helsinki/helsinki-design-system, pull requests merged in 2021-01, with the labels that each got.

#348 [Content] Added guidelines about autocomplete WCAG requirement
  site/docs/components/text_fields.mdx
Labels: documentation

#343 [Feature] Tabs
  packages/react/.loki/reference/chrome_iphone7_Components_Tabs_Default.png
  packages/react/.loki/reference/chrome_iphone7_Components_Tabs_Small.png
  packages/react/.loki/reference/chrome_laptop_Components_Tabs_Default.png
  packages/react/.loki/reference/chrome_laptop_Components_Tabs_Small.png
  packages/react/package.json
  packages/react/rollup.config.js
  packages/react/src/components/index.ts
  packages/react/src/components/tabs/Tab.tsx
  packages/react/src/components/tabs/TabList.tsx
  packages/react/src/components/tabs/TabPanel.tsx
  packages/react/src/components/tabs/Tabs.module.scss
  packages/react/src/components/tabs/Tabs.stories.tsx
  packages/react/src/components/tabs/Tabs.test.tsx
  packages/react/src/components/tabs/Tabs.tsx
  packages/react/src/components/tabs/TabsContext.ts
  packages/react/src/components/tabs/__snapshots__/Tabs.test.tsx.snap
  packages/react/src/components/tabs/index.ts
  packages/react/src/components/tabs/tabUtils.ts
  site/docs/components/component_overview.mdx
  site/docs/components/tabs.mdx
  yarn.lock
Labels: component

#356 [FIX] Optimize focus outline animation to prevent glitches
  packages/core/src/components/text-input/text-input.css
Labels: bug

#355 [FIX] Fix a bug related to cleaning of the notification area.
  packages/react/src/components/loadingSpinner/useNotificationArea.ts
Labels: bug

#353 Update Component statuses in the documentation
  site/docs/components/accordion.mdx
  site/docs/components/card.mdx
  site/docs/components/component_overview.mdx
  site/docs/components/selection_group.mdx
  site/docs/components/spinner.mdx
  site/docs/components/tabs.mdx
  site/docs/components/tag.mdx
  site/docs/components/tooltip.mdx
Labels: documentation

#345 [Feature] Search Input as core component
  packages/core/src/components/all.css
  packages/core/src/components/search-input/search-input.css
  packages/core/src/components/search-input/search-input.stories.js
  site/docs/components/component_overview.mdx
  site/docs/components/search_input.mdx
Labels: component
