Repository City-of-Helsinki/helsinki-design-system, pull requests merged in 2021-08, with the labels that each got.

#489 Fix/Fix ts-lint warning
  packages/react/src/components/footer/footerBase/FooterBase.test.tsx
Labels: enhancement

#488 Fix/Tooltip focus style
  packages/core/src/components/text-input/text-input.css
Labels: enhancement

#487 Fix/incorrect error icon
  packages/core/src/components/checkbox/checkbox.css
  packages/react/.loki/reference/chrome_iphone7_Components_Checkbox_Invalid.png
  packages/react/.loki/reference/chrome_iphone7_Components_Dropdowns_Combobox_Invalid.png
  packages/react/.loki/reference/chrome_laptop_Components_Checkbox_Invalid.png
  packages/react/.loki/reference/chrome_laptop_Components_Dropdowns_Combobox_Invalid.png
  packages/react/src/components/dropdown/combobox/Combobox.tsx
Labels: bug

#486 Fix/inline-notification-z-index
  packages/core/src/components/notification/notification.css
Labels: bug

#485 Fix/time input value on clear
  packages/react/src/components/timeInput/TimeInput.test.tsx
  packages/react/src/components/timeInput/TimeInput.tsx
Labels: bug

#484 Spelling error fixes
  site/docs/Contributing/before-contributing.mdx
  site/docs/Contributing/design.mdx
  site/docs/Contributing/making-icons.mdx
  site/docs/about/new.mdx
  site/docs/about/statement.mdx
  site/docs/components/accordion.mdx
  site/docs/components/buttons.mdx
  site/docs/components/card.mdx
  site/docs/components/component_overview.mdx
  site/docs/components/koros.mdx
  site/docs/components/logo.mdx
  site/docs/components/navigation.mdx
  site/docs/components/search_input.mdx
  site/docs/components/spinner.mdx
  site/docs/components/tag.mdx
  site/docs/components/toggle.mdx
  site/docs/components/tooltip.mdx
  site/docs/design_tokens/colour.mdx
  site/docs/design_tokens/typography.mdx
  site/docs/get_started/for_designers.mdx
  site/docs/get_started/for_developers.mdx
  site/docs/guidelines/accessibility.mdx
  site/docs/patterns/form_validation.mdx
Labels: documentation, enhancement

#490 Documentation/Guideline for implementation
  site/docs/Contributing/implemenation.mdx
Labels: documentation

#492 Update roadmap.mdx
  site/docs/about/roadmap.mdx
Labels: documentation, enhancement

#479 [Content] Getting started with Abstract tutorial
  site/docs/get_started/for_designers.mdx
  site/docs/tutorials/abstract-getting-started.mdx
  site/doczrc.js
  site/static/fordesigners-abstract-create-new-file.png
  site/static/fordesigners-abstract-create-new-project.png
  site/static/fordesigners-abstract-link-libraries-2.png
  site/static/fordesigners-abstract-link-libraries-3.png
  site/static/fordesigners-abstract-link-libraries.png
  site/static/fordesigners-component-insert.png
  site/static/fordesigners-hds-designkit.png
  site/static/tutorials/abstract-getting-started/abstract-create-branch-button.png
  site/static/tutorials/abstract-getting-started/abstract-create-new-project.png
  site/static/tutorials/abstract-getting-started/abstract-first-sketch-file.png
  site/static/tutorials/abstract-getting-started/abstract-link-libraries-button.png
  site/static/tutorials/abstract-getting-started/abstract-link-libraries.png
  site/static/tutorials/abstract-getting-started/abstract-merge-branch-button.png
  site/static/tutorials/abstract-getting-started/abstract-merge-conflicts.png
  site/static/tutorials/abstract-getting-started/abstract-new-project-button.png
  site/static/tutorials/abstract-getting-started/abstract-project-description.png
  site/static/tutorials/abstract-getting-started/abstract-update-from-master.png
  site/static/tutorials/abstract-getting-started/sketch-commit-window.png
  site/static/tutorials/abstract-getting-started/sketch-library-update-notification.png
  site/static/tutorials/abstract-getting-started/sketch-update-libraries.png
  site/static/tutorials/abstract-getting-started/sketch-use-hds-components.png
Labels: documentation

#482 [Fix] Fixed broken anchor link in the date picker documentation page
  site/docs/components/date_input.mdx
Labels: bug, documentation

#480 [Change] Add a note about Sketch Assistant link requiring Sketch to be installed
  site/docs/Contributing/design.mdx
Labels: documentation, enhancement

#481 [Content] Added links to Abstract collection to Designers getting started page
  site/docs/get_started/for_designers.mdx
Labels: documentation, enhancement

#483 Feature/link
  packages/core/src/components/all.css
  packages/core/src/components/link/link.css
  packages/core/src/components/link/link.stories.js
  packages/react/.loki/reference/chrome_iphone7_Components_Link_Default.png
  packages/react/.loki/reference/chrome_iphone7_Components_Link_External_links.png
  packages/react/.loki/reference/chrome_iphone7_Components_Link_Inline_links.png
  packages/react/.loki/reference/chrome_iphone7_Components_Link_Internal_links.png
  packages/react/.loki/reference/chrome_iphone7_Components_Link_Link_that_opens_in_a_new_tab.png
  packages/react/.loki/reference/chrome_iphone7_Components_Link_Link_without_visited_styles.png
  packages/react/.loki/reference/chrome_iphone7_Components_Link_Standalone_link.png
  packages/react/.loki/reference/chrome_iphone7_Components_Link_With_a_custom_icon.png
  packages/react/.loki/reference/chrome_laptop_Components_Link_Default.png
  packages/react/.loki/reference/chrome_laptop_Components_Link_External_links.png
  packages/react/.loki/reference/chrome_laptop_Components_Link_Inline_links.png
  packages/react/.loki/reference/chrome_laptop_Components_Link_Internal_links.png
  packages/react/.loki/reference/chrome_laptop_Components_Link_Link_that_opens_in_a_new_tab.png
  packages/react/.loki/reference/chrome_laptop_Components_Link_Link_without_visited_styles.png
  packages/react/.loki/reference/chrome_laptop_Components_Link_Standalone_link.png
  packages/react/.loki/reference/chrome_laptop_Components_Link_With_a_custom_icon.png
  packages/react/rollup.config.js
  packages/react/src/components/index.ts
  packages/react/src/components/link/Link.module.scss
  packages/react/src/components/link/Link.stories.tsx
  packages/react/src/components/link/Link.test.tsx
  packages/react/src/components/link/Link.tsx
  packages/react/src/components/link/__snapshots__/Link.test.tsx.snap
  packages/react/src/components/link/index.ts
  packages/react/src/utils/getTextFromReactChildren.ts
  site/docs/components/link.mdx
Labels: component

#500 Feature | Support clearing DateInput value programmatically
  packages/react/.loki/reference/chrome_iphone7_Components_DateInput_With_external_clear_value_button.png
  packages/react/.loki/reference/chrome_laptop_Components_DateInput_With_external_clear_value_button.png
  packages/react/.storybook/index.css
  packages/react/src/components/dateInput/DateInput.stories.tsx
  packages/react/src/components/dateInput/DateInput.test.tsx
  packages/react/src/components/dateInput/DateInput.tsx
  packages/react/src/components/dateInput/components/datePicker/DatePicker.tsx
  packages/react/src/components/passwordInput/PasswordInput.stories.tsx
Labels: bug

#506 [bug-fixing] Fix Navigation component render when optional label property is missing
  packages/react/src/components/notification/Notification.test.tsx
  packages/react/src/components/notification/Notification.tsx
  packages/react/src/components/notification/__snapshots__/Notification.test.tsx.snap
Labels: bug

#507 [bug-fixing] Add lang-attributes to Navigation.LanguageSelector examples
  packages/react/src/components/navigation/Navigation.stories.tsx
  packages/react/src/components/navigation/navigationLanguageSelector/NavigationLanguageSelector.tsx
  site/docs/components/navigation.mdx
Labels: bug

#508 [Change] Update color-tram token value
  packages/design-tokens/tokens/color/brand/tram.json
  packages/react/.loki/reference/chrome_iphone7_Components_LoadingSpinner_Custom_theme.png
  packages/react/.loki/reference/chrome_iphone7_Components_ToggleButton_Custom_theme.png
  packages/react/.loki/reference/chrome_laptop_Components_LoadingSpinner_Custom_theme.png
  packages/react/.loki/reference/chrome_laptop_Components_ToggleButton_Custom_theme.png
  site/docs/design_tokens/colour.mdx
Labels: enhancement, token

#510 [bug-fixing] Remove border radius from navigation focus style
  packages/react/src/components/navigation/Navigation.module.scss
  packages/react/src/components/navigation/navigationItem/NavigationItem.module.scss
  packages/react/src/components/navigation/navigationSearch/NavigationSearch.module.scss
  packages/react/src/components/navigation/navigationUser/NavigationUser.module.scss
  packages/react/src/internal/menuButton/MenuButton.module.scss
Labels: bug

#511 [bug fixing] Pass native event to onTitleClick
  packages/react/src/components/navigation/Navigation.tsx
Labels: enhancement

#512 [bug fixing] Fix github template labels
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/question.md
Labels: bug

#478 [Content] Side navigation documentation
  site/docs/components/component_overview.mdx
  site/docs/components/side_navigation.mdx
Labels: documentation
