Repository City-of-Helsinki/helsinki-design-system, pull requests merged in 2021-12, with the labels that each got.

#605 Fix date input focus disappear bug
  packages/react/src/components/dateInput/DateInput.stories.tsx
  packages/react/src/components/dateInput/__snapshots__/DateInput.test.tsx.snap
  packages/react/src/components/dateInput/components/datePicker/DatePicker.module.scss
  packages/react/src/components/dateInput/components/monthNavigation/MonthNavigation.tsx
Labels: bug

#598 [Fix] add support to remove selectedItem with an enter and space keypress
  packages/react/src/components/dropdown/combobox/Combobox.test.tsx
  packages/react/src/internal/selectedItems/SelectedItems.tsx
Labels: bug, waiting-for-accessibility-audit

#599 [Feature] Icon set 12/2021
  packages/core/src/icons/all.css
  packages/core/src/icons/ui/icon-arrow-bottom-left.css
  packages/core/src/icons/ui/icon-arrow-bottom-right.css
  packages/core/src/icons/ui/icon-arrow-top-left.css
  packages/core/src/icons/ui/icon-arrow-top-right.css
  packages/core/src/icons/ui/icon-coffee-cup-saucer.css
  packages/core/src/icons/ui/icon-copy.css
  packages/core/src/icons/ui/icon-event.css
  packages/core/src/icons/ui/icon-restaurant.css
  packages/core/src/icons/ui/icon-sitemap.css
  packages/core/src/svg/ui/arrow-bottom-left.svg
  packages/core/src/svg/ui/arrow-bottom-right.svg
  packages/core/src/svg/ui/arrow-top-left.svg
  packages/core/src/svg/ui/arrow-top-right.svg
  packages/core/src/svg/ui/coffee-cup-saucer.svg
  packages/core/src/svg/ui/copy.svg
  packages/core/src/svg/ui/event.svg
  packages/core/src/svg/ui/restaurant.svg
  packages/core/src/svg/ui/sitemap.svg
  packages/react/src/icons/index.ts
  packages/react/src/icons/ui/IconArrowBottomLeft.tsx
  packages/react/src/icons/ui/IconArrowBottomRight.tsx
  packages/react/src/icons/ui/IconArrowTopLeft.tsx
  packages/react/src/icons/ui/IconArrowTopRight.tsx
  packages/react/src/icons/ui/IconCoffeeCupSaucer.tsx
  packages/react/src/icons/ui/IconCopy.tsx
  packages/react/src/icons/ui/IconEvent.tsx
  packages/react/src/icons/ui/IconRestaurant.tsx
  packages/react/src/icons/ui/IconSitemap.tsx
  site/docs/visual_elements/icons.mdx
Labels: documentation, component
