Repository City-of-Helsinki/helsinki-design-system, pull requests merged in 2022-03, with the labels that each got.

#686 Feature/indeterminate checkbox
  packages/core/src/components/checkbox/checkbox.css
  packages/core/src/components/checkbox/checkbox.stories.js
  packages/core/src/components/selection-group/selection-group.stories.js
  packages/react/.loki/reference/chrome_iphone7_Components_Checkbox_Checkbox_Group.png
  packages/react/.loki/reference/chrome_iphone7_Components_Checkbox_Group_with_a_parent.png
  packages/react/.loki/reference/chrome_iphone7_Components_Checkbox_Indeterminate.png
  packages/react/.loki/reference/chrome_iphone7_Components_Checkbox_Indeterminated.png
  packages/react/.loki/reference/chrome_iphone7_Components_Checkbox_Playground.png
  packages/react/.loki/reference/chrome_laptop_Components_Checkbox_Checkbox_Group.png
  packages/react/.loki/reference/chrome_laptop_Components_Checkbox_Group_with_a_parent.png
  packages/react/.loki/reference/chrome_laptop_Components_Checkbox_Indeterminate.png
  packages/react/.loki/reference/chrome_laptop_Components_Checkbox_Indeterminated.png
  packages/react/.loki/reference/chrome_laptop_Components_Checkbox_Playground.png
  packages/react/src/components/checkbox/Checkbox.stories.tsx
  packages/react/src/components/checkbox/Checkbox.tsx
  packages/react/src/components/selectionGroup/SelectionGroup.stories.tsx
  site/docs/components/checkbox.mdx
Labels: enhancement, component

#687 [Content] Getting started and Guidelines sections to the new documentation page
  new-site/gatsby-config.js
  new-site/src/docs/about/accessibility/hds-accessibility.mdx
  new-site/src/docs/about/accessibility/statement.mdx
  new-site/src/docs/getting-started/contributing/before-contributing.mdx
  new-site/src/docs/getting-started/contributing/design.mdx
  new-site/src/docs/getting-started/contributing/documentation.mdx
  new-site/src/docs/getting-started/contributing/icons.mdx
  new-site/src/docs/getting-started/contributing/implementation.mdx
  new-site/src/docs/getting-started/designer.mdx
  new-site/src/docs/getting-started/developer.mdx
  new-site/src/docs/getting-started/faq/accessibility.mdx
  new-site/src/docs/getting-started/faq/code.mdx
  new-site/src/docs/getting-started/faq/design.mdx
  new-site/src/docs/getting-started/faq/general.mdx
  new-site/src/docs/getting-started/faq/index.mdx
  new-site/src/docs/getting-started/index.mdx
  new-site/src/docs/getting-started/tutorials/abstract-tutorial.mdx
  new-site/src/docs/getting-started/tutorials/guide-to-v1.mdx
  new-site/src/docs/guidelines/checkbox-radiobutton-toggle.mdx
  new-site/src/docs/guidelines/data-formats.mdx
  new-site/src/docs/guidelines/faq.mdx
  new-site/src/docs/guidelines/grid.mdx
  new-site/src/docs/guidelines/inclusivity.mdx
  new-site/src/docs/guidelines/localisation.mdx
  new-site/src/docs/guidelines/photography.mdx
  new-site/src/images/getting-started/designer/component-overrides.png
  new-site/src/images/getting-started/designer/typography-header-insert.png
  new-site/src/images/getting-started/designer/typography-textstyle-appearance.png
  new-site/src/images/getting-started/hds-building-blocks.png
  new-site/src/images/getting-started/tutorials/abstract-basics/abstract-create-branch-button.png
  new-site/src/images/getting-started/tutorials/abstract-basics/abstract-create-new-project.png
  new-site/src/images/getting-started/tutorials/abstract-basics/abstract-first-sketch-file.png
  new-site/src/images/getting-started/tutorials/abstract-basics/abstract-link-libraries-button.png
  new-site/src/images/getting-started/tutorials/abstract-basics/abstract-link-libraries.png
  new-site/src/images/getting-started/tutorials/abstract-basics/abstract-merge-branch-button.png
  new-site/src/images/getting-started/tutorials/abstract-basics/abstract-merge-conflicts.png
  new-site/src/images/getting-started/tutorials/abstract-basics/abstract-new-project-button.png
  new-site/src/images/getting-started/tutorials/abstract-basics/abstract-project-description.png
  new-site/src/images/getting-started/tutorials/abstract-basics/abstract-update-from-master.png
  new-site/src/images/getting-started/tutorials/abstract-basics/sketch-commit-window.png
  new-site/src/images/getting-started/tutorials/abstract-basics/sketch-library-update-notification.png
  new-site/src/images/getting-started/tutorials/abstract-basics/sketch-update-libraries.png
  new-site/src/images/getting-started/tutorials/abstract-basics/sketch-use-hds-components.png
  new-site/src/images/guidelines/grid/breakpoint-demonstration.png
  new-site/src/images/guidelines/grid/column-stacking.png
  new-site/src/images/guidelines/grid/layout-columns.png
Labels: documentation

#694 [Fix] FAQ and Accessibility pages now show up in the side navigation
  new-site/src/docs/about/accessibility/hds-accessibility.mdx
  new-site/src/docs/about/accessibility/statement.mdx
  new-site/src/docs/getting-started/faq/accessibility.mdx
  new-site/src/docs/getting-started/faq/general.mdx
  new-site/src/docs/getting-started/tutorials/abstract-tutorial.mdx
  new-site/src/docs/getting-started/tutorials/guide-to-v1.mdx
Labels: bug, documentation
