Repository City-of-Helsinki/helsinki-design-system, pull requests merged in 2022-01, with the labels that each got.

#619 [Content] Added an example of asking the user's gender to the Form pattern
  site/docs/patterns/forms.mdx
  site/static/patterns/form/form-asking-for-gender-example@2x.png
Labels: documentation, enhancement

#616 Restrict node version because of node-sass
  packages/react/package.json
Labels: dependencies

#617 Update new-site dependencies
  new-site/package.json
  new-site/yarn.lock
Labels: dependencies

#625 backToTopButton move focus to first visible focusable element
  packages/react/src/components/footer/footerUtilities/FooterUtilities.test.tsx
  packages/react/src/utils/getKeyboardFocusableElements.ts
Labels: bug

#626 [Content] Added a visual documentation page for Koro shapes
  site/docs/visual_elements/koros.mdx
  site/static/visual/koros/allowed-koro-angles@2x.png
  site/static/visual/koros/koro-accent-usage@2x.png
  site/static/visual/koros/koro-colour-usage@2x.png
  site/static/visual/koros/koro-shapes@2x.png
  site/static/visual/koros/koro-sizes-and-aligment@2x.png
  site/static/visual/koros/koro-sizes@2x.png
  site/static/visual/koros/koro-usage-edge-of-section@2x.png
  site/static/visual/koros/koro-usage-in-content-sections@2x.png
  site/static/visual/koros/koro-usage-visually-separate-elements@2x.png
  site/static/visual/koros/koro-with-an-image@2x.png
  site/static/visual/koros/mixing-koro-shapes-and-sizes@2x.png
Labels: documentation

#633 [Fix] Add border-radius to TextInput and TextArea to prevent rounded corners on iOS
  packages/core/src/components/text-input/text-input.css
Labels: bug

#634 [Content] New documentation site FAQ page
  new-site/gatsby-config.js
  new-site/src/components/layout.scss
  new-site/src/docs/guidelines/faq.mdx
Labels: documentation
