Repository City-of-Helsinki/helsinki-design-system, pull requests merged in 2022-09, with the labels that each got.

#815 Feature/react pagination
  packages/core/src/components/pagination/pagination.css
  packages/react/.loki/reference/chrome_iphone7_Components_Pagination_Basic.png
  packages/react/.loki/reference/chrome_iphone7_Components_Pagination_Custom_theme.png
  packages/react/.loki/reference/chrome_iphone7_Components_Pagination_With_truncation.png
  packages/react/.loki/reference/chrome_iphone7_Components_Pagination_Without_prev_and_next_buttons.png
  packages/react/.loki/reference/chrome_laptop_Components_Pagination_Basic.png
  packages/react/.loki/reference/chrome_laptop_Components_Pagination_Custom_theme.png
  packages/react/.loki/reference/chrome_laptop_Components_Pagination_With_truncation.png
  packages/react/.loki/reference/chrome_laptop_Components_Pagination_Without_prev_and_next_buttons.png
  packages/react/rollup.config.js
  packages/react/src/components/index.ts
  packages/react/src/components/pagination/Pagination.module.scss
  packages/react/src/components/pagination/Pagination.stories.tsx
  packages/react/src/components/pagination/Pagination.test.tsx
  packages/react/src/components/pagination/Pagination.tsx
  packages/react/src/components/pagination/__snapshots__/Pagination.test.tsx.snap
  packages/react/src/components/pagination/index.ts
  packages/react/src/hooks/useTheme.tsx
  site/src/components/ComponentsList.js
  site/src/docs/components/pagination/accessibility.mdx
  site/src/docs/components/pagination/code.mdx
  site/src/docs/components/pagination/customisation.mdx
  site/src/docs/components/pagination/index.mdx
  site/src/docs/components/pagination/tabs.mdx
Labels: component

#812 Feature/notification custom aria label
  packages/react/src/components/link/Link.tsx
  packages/react/src/components/linkbox/Linkbox.tsx
  packages/react/src/components/notification/Notification.stories.tsx
  packages/react/src/components/notification/Notification.tsx
  packages/react/src/components/numberInput/NumberInput.tsx
  packages/react/src/components/passwordInput/PasswordInput.tsx
  packages/react/src/components/sideNavigation/mainLevel/MainLevel.tsx
  packages/react/src/components/stepper/Step.tsx
  packages/react/src/components/stepper/Stepper.tsx
  site/src/docs/components/notification/code.mdx
Labels: enhancement

#819 Component customisation docs revisited
  site/src/docs/components/buttons/customisation.mdx
  site/src/docs/components/card/customisation.mdx
  site/src/docs/components/checkbox/customisation.mdx
  site/src/docs/components/koros/customisation.mdx
  site/src/docs/components/loading-spinner/customisation.mdx
  site/src/docs/components/logo/customisation.mdx
  site/src/docs/components/pagination/customisation.mdx
  site/src/docs/components/radio-button/customisation.mdx
  site/src/docs/components/stepper/customisation.mdx
  site/src/docs/components/table/customisation.mdx
  site/src/docs/components/tabs/customisation.mdx
  site/src/docs/components/tag/customisation.mdx
Labels: documentation

#843 HDS-1416 Fix docsite Table customisation page theme variables
  site/src/docs/components/table/customisation.mdx
Labels: documentation
