Repository City-of-Helsinki/helsinki-design-system, pull requests merged in 2022-06, with the labels that each got.

#738 Docsite/component overview
  new-site/.eslintignore
  new-site/package.json
  new-site/src/components/ComponentsList.js
  new-site/src/components/ComponentsList.scss
  new-site/src/docs/components/index.mdx
Labels: documentation

#723 [Content/Fix] Adding missing documentation content
  new-site/src/docs/about/what-is-new.mdx
  new-site/src/docs/components/checkbox/code.mdx
  new-site/src/docs/components/checkbox/index.mdx
  new-site/src/docs/components/date-input/code.mdx
  new-site/src/docs/components/date-input/index.mdx
  new-site/src/docs/components/footer/code.mdx
  new-site/src/docs/components/icon/accessibility.mdx
  new-site/src/docs/components/icon/code.mdx
  new-site/src/docs/components/icon/index.mdx
  new-site/src/docs/components/koros/code.mdx
  new-site/src/docs/components/koros/index.mdx
  new-site/src/docs/components/linkbox/code.mdx
  new-site/src/docs/components/linkbox/index.mdx
  new-site/src/docs/components/logo/code.mdx
  new-site/src/docs/components/logo/customisation.mdx
  new-site/src/docs/components/logo/index.mdx
  new-site/src/docs/components/pagination/accessibility.mdx
  new-site/src/docs/components/pagination/code.mdx
  new-site/src/docs/components/pagination/customisation.mdx
  new-site/src/docs/components/pagination/index.mdx
  new-site/src/docs/components/pagination/tabs.mdx
  new-site/src/docs/components/toggle-button/customisation.mdx
  new-site/src/docs/foundation/design-tokens/colour/tokens.mdx
  new-site/src/docs/foundation/design-tokens/typography/index.mdx
  new-site/src/docs/foundation/guidelines/checkbox-radiobutton-toggle.mdx
  new-site/src/docs/foundation/visual-assets/icons.mdx
  new-site/src/docs/foundation/visual-assets/icons/index.mdx
  new-site/src/docs/foundation/visual-assets/icons/list.mdx
  new-site/src/docs/foundation/visual-assets/icons/tabs.mdx
  new-site/src/docs/foundation/visual-assets/logo.mdx
  new-site/src/docs/foundation/visual-assets/wave-motifs.mdx
  new-site/src/docs/getting-started/contributing/design.mdx
  new-site/src/docs/getting-started/faq/accessibility.mdx
  new-site/src/docs/getting-started/faq/code.mdx
  new-site/src/docs/getting-started/faq/design.mdx
  new-site/src/docs/getting-started/faq/index.mdx
  new-site/static/images/foundation/visual-assets/icons/icon-sizes.png
  new-site/static/images/foundation/visual-assets/wave-motifs/koro-colour-usage@2x.png
  site/static/visual/koros/koro-colour-usage@2x.png
Labels: documentation, enhancement

#759 Content/Add favicon to new documentation site
  new-site/gatsby-config.js
  new-site/src/components/Seo.js
  new-site/static/favicon/transparent_dark_favicon_package/android-chrome-192x192.png
  new-site/static/favicon/transparent_dark_favicon_package/android-chrome-256x256.png
  new-site/static/favicon/transparent_dark_favicon_package/apple-touch-icon.png
  new-site/static/favicon/transparent_dark_favicon_package/favicon-16x16.png
  new-site/static/favicon/transparent_dark_favicon_package/favicon-32x32.png
  new-site/static/favicon/transparent_light_favicon_package/android-chrome-192x192.png
  new-site/static/favicon/transparent_light_favicon_package/android-chrome-256x256.png
  new-site/static/favicon/transparent_light_favicon_package/apple-touch-icon.png
  new-site/static/favicon/transparent_light_favicon_package/favicon-16x16.png
  new-site/static/favicon/transparent_light_favicon_package/favicon-32x32.png
Labels: documentation

#748 [Content] HDS 2.0 guide pages
  new-site/gatsby-config.js
  new-site/src/docs/getting-started/hds-2.0/fi/mika-on-hds-2.0.mdx
  new-site/src/docs/getting-started/hds-2.0/migrating-to-2.0.mdx
  new-site/src/docs/getting-started/hds-2.0/what-is-hds-2.0.mdx
  new-site/src/docs/getting-started/tutorials/guide-to-v1.mdx
  new-site/static/images/getting-started/hds-2.0/accordion-before-after-fi.png
  new-site/static/images/getting-started/hds-2.0/accordion-before-after.png
  new-site/static/images/getting-started/hds-2.0/container-before-after-fi.png
  new-site/static/images/getting-started/hds-2.0/container-before-after.png
  new-site/static/images/getting-started/hds-2.0/typography-before-after-fi.png
  new-site/static/images/getting-started/hds-2.0/typography-before-after.png
  storybook-static/favicon.ico
Labels: documentation

#760 [Content] Update component statuses for the 2.0 documentation
  new-site/src/docs/components/file-input/tabs.mdx
  new-site/src/docs/components/footer/tabs.mdx
  new-site/src/docs/components/linkbox/tabs.mdx
  new-site/src/docs/components/navigation/tabs.mdx
  new-site/src/docs/components/search-input/tabs.mdx
  new-site/src/docs/components/side-navigation/tabs.mdx
  new-site/src/docs/components/stepper/tabs.mdx
Labels: documentation

#711 Change/delete deprecated variables
  new-site/src/docs/components/accordion/customisation.mdx
  packages/core/src/components/table/table.css
  packages/react/src/components/accordion/Accordion.tsx
  packages/react/src/components/table/Table.tsx
  site/docs/components/accordion.mdx
Labels: Breaking changes

#725 Change/Dialog spacing
  packages/react/.loki/reference/chrome_iphone7_Components_Dialog_Confirmation.png
  packages/react/.loki/reference/chrome_iphone7_Components_Dialog_Danger.png
  packages/react/.loki/reference/chrome_iphone7_Components_Dialog_Scrollable_confirmation.png
  packages/react/.loki/reference/chrome_iphone7_Components_Dialog_With_box_shadow.png
  packages/react/.loki/reference/chrome_iphone7_Components_Dialog_With_long_button_labels.png
  packages/react/.loki/reference/chrome_laptop_Components_Dialog_Confirmation.png
  packages/react/.loki/reference/chrome_laptop_Components_Dialog_Danger.png
  packages/react/.loki/reference/chrome_laptop_Components_Dialog_Scrollable_confirmation.png
  packages/react/.loki/reference/chrome_laptop_Components_Dialog_With_box_shadow.png
  packages/react/.loki/reference/chrome_laptop_Components_Dialog_With_long_button_labels.png
  packages/react/src/components/dialog/Dialog.stories.tsx
  packages/react/src/components/dialog/dialogHeader/DialogHeader.module.scss
Labels: Breaking changes

#773 [Content] Accordion closeButton documentation
  new-site/src/docs/components/accordion/code.mdx
  new-site/src/docs/components/accordion/index.mdx
Labels: documentation

#770 [Fix] Documentation site accessibility audit issues
  new-site/gatsby-config.js
  new-site/src/components/layout.js
  new-site/src/docs/about/accessibility/statement.mdx
  new-site/src/docs/components/accordion/index.mdx
  new-site/src/docs/components/checkbox/code.mdx
  new-site/src/docs/components/checkbox/index.mdx
  new-site/src/docs/components/fieldset/code.mdx
  new-site/src/docs/components/fieldset/index.mdx
  new-site/src/docs/components/file-input/code.mdx
  new-site/src/docs/components/password-input/code.mdx
  new-site/src/docs/components/password-input/index.mdx
  new-site/src/docs/components/phone-input/code.mdx
  new-site/src/docs/components/radio-button/code.mdx
  new-site/src/docs/components/text-area/code.mdx
  new-site/src/docs/components/text-area/index.mdx
  new-site/src/docs/components/text-input/code.mdx
  new-site/src/docs/components/text-input/index.mdx
  new-site/src/docs/components/time-input/code.mdx
  new-site/src/docs/components/time-input/index.mdx
  new-site/src/docs/components/toggle-button/code.mdx
  new-site/src/docs/components/toggle-button/index.mdx
  new-site/src/docs/foundation/guidelines/grid.mdx
  new-site/src/docs/foundation/visual-assets/wave-motifs.mdx
  new-site/src/docs/getting-started/contributing/before-contributing.mdx
  new-site/src/docs/getting-started/hds-2.0/fi/mika-on-hds-2.0.mdx
  new-site/src/docs/getting-started/hds-2.0/what-is-hds-2.0.mdx
  new-site/src/docs/getting-started/tutorials/abstract-tutorial.mdx
  new-site/src/docs/index.mdx
Labels: bug, documentation

#776 [Fix] Minor 2.0 docsite fixes
  new-site/src/docs/components/buttons/code.mdx
  new-site/src/docs/components/card/code.mdx
  new-site/src/docs/components/checkbox/code.mdx
  new-site/src/docs/components/linkbox/code.mdx
Labels: bug, documentation

#782 [Fix] Typography heading examples
  site/src/docs/foundation/design-tokens/typography/index.mdx
Labels: bug, documentation

#781 [Content] 2.0 design guide improvements
  site/src/docs/getting-started/hds-2.0/fi/mika-on-hds-2.0.mdx
  site/src/docs/getting-started/hds-2.0/what-is-hds-2.0.mdx
Labels: documentation, enhancement

#783 [Fix] Incorrect mention about a removed table theme variable
  CHANGELOG.md
  site/src/docs/getting-started/hds-2.0/migrating-to-2.0.mdx
Labels: bug, documentation

#739 [Fix] Make DialogContent scrollable only if scrollable prop is true
  packages/react/src/components/dialog/Dialog.stories.tsx
  packages/react/src/components/dialog/dialogContent/DialogContent.module.scss
Labels: bug
