Repository City-of-Helsinki/helsinki-design-system, pull requests merged in 2022-07, with the labels that each got.

#790 Remove volatile css-module declaration
  packages/react/src/components/navigation/Navigation.module.scss
Labels: bug

#800 Fix browser console warnings
  site/src/components/ExternalLink.js
Labels: documentation, enhancement

#799 Fix/Vertical alignment of included icon and text for docsite components
  site/src/docs/components/accordion/code.mdx
  site/src/docs/components/buttons/code.mdx
  site/src/docs/components/card/code.mdx
  site/src/docs/components/checkbox/code.mdx
  site/src/docs/components/date-input/code.mdx
  site/src/docs/components/dialog/code.mdx
  site/src/docs/components/dropdown/code.mdx
  site/src/docs/components/fieldset/code.mdx
  site/src/docs/components/file-input/code.mdx
  site/src/docs/components/footer/code.mdx
  site/src/docs/components/icon/code.mdx
  site/src/docs/components/koros/code.mdx
  site/src/docs/components/link/code.mdx
  site/src/docs/components/linkbox/code.mdx
  site/src/docs/components/loading-spinner/code.mdx
  site/src/docs/components/logo/code.mdx
  site/src/docs/components/navigation/code.mdx
  site/src/docs/components/notification/code.mdx
  site/src/docs/components/number-input/code.mdx
  site/src/docs/components/pagination/code.mdx
  site/src/docs/components/password-input/code.mdx
  site/src/docs/components/phone-input/code.mdx
  site/src/docs/components/radio-button/code.mdx
  site/src/docs/components/search-input/code.mdx
  site/src/docs/components/selection-group/code.mdx
  site/src/docs/components/side-navigation/code.mdx
  site/src/docs/components/status-label/code.mdx
  site/src/docs/components/stepper/code.mdx
  site/src/docs/components/table/code.mdx
  site/src/docs/components/tabs/code.mdx
  site/src/docs/components/tag/code.mdx
  site/src/docs/components/text-area/code.mdx
  site/src/docs/components/text-input/code.mdx
  site/src/docs/components/time-input/code.mdx
  site/src/docs/components/toggle-button/code.mdx
  site/src/docs/components/tooltip/code.mdx
Labels: bug, documentation

#798 Fix Accordion and Stepper component font-sizes
  site/src/components/layout.scss
Labels: bug, documentation

#805 Content/Add Linkbox size variants to documentation site
  site/src/docs/components/linkbox/code.mdx
  site/src/docs/components/linkbox/index.mdx
Labels: documentation

#807 Fix/Broken link in docsite button accessibility page
  site/src/docs/components/buttons/accessibility.mdx
Labels: bug
